const API='https://api.upstox.com/v3';
const NSE='https://archives.nseindia.com/content/indices/ind_nifty500list.csv';
const FALLBACK='https://raw.githubusercontent.com/ganeshbiyer/Nse_Historical_Data/main/nifty500_symbols.csv';
const token=()=>process.env.UPSTOX_ANALYTICS_TOKEN||'';
const cache=new Map();
async function fetchT(url,opts={},ms=7000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{...opts,signal:c.signal,cache:'no-store'})}finally{clearTimeout(t)}}
async function jget(url,ms=9000){const r=await fetchT(url,{headers:{Accept:'application/json',Authorization:`Bearer ${token()}`}},ms);const text=await r.text();let body={};try{body=JSON.parse(text)}catch{}return[r.status,body]}
function parseCSV(t){const rows=t.replace(/^\uFEFF/,'').trim().split(/\r?\n/);if(!rows.length)return[];const h=rows.shift().split(',').map(x=>x.trim().replace(/^\"|\"$/g,''));return rows.map(line=>{const v=[];let cur='',q=false;for(const ch of line){if(ch==='\"')q=!q;else if(ch===','&&!q){v.push(cur);cur=''}else cur+=ch}v.push(cur);const o={};h.forEach((k,i)=>o[k]=(v[i]||'').trim());return o})}
async function getNiftyRows(){let text='';try{const r=await fetchT(NSE,{headers:{'User-Agent':'Mozilla/5.0','Accept':'text/csv,*/*'}},5000);if(r.ok)text=await r.text()}catch{}if(!text){const r=await fetchT(FALLBACK,{},5000);if(!r.ok)throw new Error(`NIFTY 500 list unavailable (HTTP ${r.status})`);text=await r.text()}const p=parseCSV(text),k=p.length&&Object.keys(p[0]).find(x=>x.toLowerCase()==='symbol');if(!k)throw new Error('NIFTY 500 list format not recognised');return p.map(x=>String(x[k]||'').trim().toUpperCase()).filter(Boolean).slice(0,500)}
async function resolveSymbol(symbol){if(cache.has(symbol))return cache.get(symbol);const url='https://api.upstox.com/v2/instruments/search?query='+encodeURIComponent(symbol)+'&exchanges=NSE&segments=EQ&records=30';const[s,j]=await jget(url,9000);if(s!==200)throw new Error(j?.errors?.[0]?.message||`Instrument search ${s}`);const a=(j.data||[]).filter(x=>x.segment==='NSE_EQ'&&['EQ','BE'].includes(x.instrument_type)),exact=a.find(x=>String(x.trading_symbol).toUpperCase()===symbol);if(!exact)throw new Error(`Instrument not found: ${symbol}`);const z={symbol,company:exact.name||symbol,industry:'NIFTY 500',instrumentKey:exact.instrument_key};cache.set(symbol,z);return z}
async function resolveMany(symbols){const out=[];for(let i=0;i<symbols.length;i+=10){const g=await Promise.all(symbols.slice(i,i+10).map(s=>resolveSymbol(s).catch(()=>null)));g.filter(Boolean).forEach(x=>out.push(x))}return out}
const candle=x=>({ts:x[0],o:+x[1],h:+x[2],l:+x[3],c:+x[4],v:+x[5]});
const exciting=x=>{const r=Math.max(x.h-x.l,1e-9);return Math.abs(x.c-x.o)/r>=.5};
const base=x=>{const r=Math.max(x.h-x.l,1e-9);return Math.abs(x.c-x.o)/r<.5};
function aggregateQuarterly(months){const a=months.map(candle).sort((a,b)=>a.ts.localeCompare(b.ts)),out=[];for(let i=0;i<a.length;i+=3){const g=a.slice(i,i+3);if(g.length<3)continue;out.push({ts:g[0].ts,o:g[0].o,h:Math.max(...g.map(x=>x.h)),l:Math.min(...g.map(x=>x.l)),c:g[g.length-1].c,v:g.reduce((s,x)=>s+x.v,0)})}return out}
function zones(raw){const c=raw.map(candle).sort((a,b)=>a.ts.localeCompare(b.ts)),out=[];for(let i=1;i<c.length-1;i++){const li=c[i-1],b=c[i],lo=c[i+1];if(!base(b)||!exciting(lo))continue;const demand=lo.c>lo.o;if(demand&&li.c>=li.o)continue;if(!demand&&li.c<=li.o)continue;const proximal=demand?Math.max(b.o,b.c):Math.min(b.o,b.c),distal=demand?b.l:b.h;let tested=false;for(let j=i+2;j<c.length;j++)if(c[j].h>=distal&&c[j].l<=proximal){tested=true;break}const gap=demand?lo.l>li.h:lo.h<li.l;const strength=gap||exciting(li)?2:1;out.push({type:demand?'Demand':'Supply',proximal,distal,fresh:!tested,strength,score:Math.min(7,(!tested?3:0)+strength+2),ts:b.ts})}return out}
function weeklyTrend(raw){const c=raw.map(candle).sort((a,b)=>a.ts.localeCompare(b.ts));if(c.length<20)return'SIDEWAYS';const cl=c.map(x=>x.c),ema=p=>{const k=2/(p+1);let e=cl[0];for(let i=1;i<cl.length;i++)e=cl[i]*k+e*(1-k);return e};const e20=ema(20),e50=ema(Math.min(50,cl.length)),last=cl.at(-1);if(last>e20&&e20>e50)return'UP';if(last<e20&&e20<e50)return'DOWN';return'SIDEWAYS'}
async function hist(key,unit,interval,days){const to=new Date().toISOString().slice(0,10),d=new Date();d.setDate(d.getDate()-days);const from=d.toISOString().slice(0,10),[s,j]=await jget(`${API}/historical-candle/${encodeURIComponent(key)}/${unit}/${interval}/${to}/${from}`,10000);if(s!==200)throw new Error(j?.errors?.[0]?.message||`Historical data ${s}`);return j?.data?.candles||[]}
async function scanOne(s,type){const masterRaw=await hist(s.instrumentKey,type==='QIT'?'months':'weeks',1,type==='QIT'?3650:1825),master=type==='QIT'?aggregateQuarterly(masterRaw):masterRaw,mz=zones(master).sort((a,b)=>b.score-a.score||String(b.ts).localeCompare(String(a.ts)))[0];if(!mz)return null;let trend='—';if(type==='MIT')trend=weeklyTrend(await hist(s.instrumentKey,'weeks',1,1825));if(type==='MIT'&&((mz.type==='Demand'&&trend!=='UP')||(mz.type==='Supply'&&trend!=='DOWN')))return null;const unit=type==='QIT'?'weeks':type==='MIT'?'days':'hours',interval=type==='WIT'?'4':'1',eraw=await hist(s.instrumentKey,unit,interval,type==='WIT'?75:1095),lo=Math.min(mz.proximal,mz.distal),hi=Math.max(mz.proximal,mz.distal),ez=zones(eraw).filter(z=>(z.proximal>=lo&&z.proximal<=hi)||(z.distal>=lo&&z.distal<=hi)).sort((a,b)=>b.score-a.score)[0];if(!ez)return null;const entry=ez.type==='Demand'?ez.proximal+.01:ez.proximal-.01,risk=Math.abs(entry-ez.distal);if(!risk)return null;const quality=Math.min(50,(mz.fresh?5:0)+(ez.fresh?5:0)+(mz.strength>=2?5:3)+(ez.strength>=2?5:3)+(((trend==='UP'&&ez.type==='Demand')||(trend==='DOWN'&&ez.type==='Supply'))?10:5)+5+(ez.score>=6?5:3)+5);return{symbol:s.symbol,company:s.company,industry:s.industry,instrumentKey:s.instrumentKey,type,direction:ez.type==='Demand'?'BUY':'SELL',zoneScore:Math.min(7,ez.score),quality,location:`${type} ${mz.type}`,trend,entryTf:type==='QIT'?'Weekly':type==='MIT'?'Daily':'4H',entry,sl:ez.distal,target:ez.type==='Demand'?entry+2*risk:entry-2*risk,rr:'1:2',masterZone:{proximal:mz.proximal,distal:mz.distal,score:mz.score,fresh:mz.fresh},entryZone:{proximal:ez.proximal,distal:ez.distal,score:ez.score,fresh:ez.fresh}}}
module.exports=async(q,r)=>{try{const u=new URL(q.url,'https://gtf.local'),a=u.searchParams.get('action')||'status';if(a==='status')return r.status(200).json({connected:!!token(),mode:token()?'analytics-token':'not-configured'});if(!token())return r.status(401).json({error:'UPSTOX_ANALYTICS_TOKEN is not configured in Vercel'});if(a==='universe'){const symbols=await getNiftyRows();return r.status(200).json({data:symbols.map(symbol=>({symbol})),source:'NIFTY 500 symbol list'})}if(a==='resolve'){const symbols=(u.searchParams.get('symbols')||'').split(',').map(x=>x.trim().toUpperCase()).filter(Boolean).slice(0,25);return r.status(200).json({data:await resolveMany(symbols)})}if(a==='ltp'){const keys=u.searchParams.get('keys');if(!keys)return r.status(400).json({error:'keys required'});const[s,j]=await jget(`${API}/market-quote/ltp?instrument_key=${encodeURIComponent(keys)}`);return r.status(s).json(j)}if(a==='scan'&&q.method==='POST'){let raw='';for await(const ch of q)raw+=ch;const b=JSON.parse(raw||'{}'),type=['QIT','MIT','WIT'].includes(b.type)?b.type:'MIT',symbols=Array.isArray(b.universe)?b.universe.map(x=>typeof x==='string'?x:x.symbol).slice(0,500):[],offset=Math.max(0,+b.offset||0),limit=Math.min(25,Math.max(1,+b.limit||25)),slice=await resolveMany(symbols.slice(offset,offset+limit)),out=[];for(let i=0;i<slice.length;i+=5){const g=await Promise.all(slice.slice(i,i+5).map(s=>scanOne(s,type).catch(()=>null)));g.filter(Boolean).forEach(x=>out.push(x))}out.sort((a,b)=>b.zoneScore-a.zoneScore||b.quality-a.quality);return r.status(200).json({type,offset,limit,scanned:slice.length,total:symbols.length,done:offset+limit>=symbols.length,results:out})}return r.status(404).json({error:'Unknown action'})}catch(e){console.error(e);return r.status(500).json({error:e.name==='AbortError'?'Upstream request timed out':e.message||'Server error'})}};