const API='https://api.upstox.com/v3';
const NSE='https://archives.nseindia.com/content/indices/ind_nifty500list.csv';
const FALLBACK='https://raw.githubusercontent.com/ganeshbiyer/Nse_Historical_Data/main/nifty500_symbols.csv';
const INS='https://assets.upstox.com/market-quote/instruments/exchange/NSE.json.gz';
const token=()=>process.env.UPSTOX_ANALYTICS_TOKEN||'';
async function fetchT(url,opts={},ms=7000){const c=new AbortController();const t=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{...opts,signal:c.signal,cache:'no-store'})}finally{clearTimeout(t)}}
const jget=async url=>{const r=await fetchT(url,{headers:{Accept:'application/json',Authorization:`Bearer ${token()}`}},10000);const text=await r.text();let body={};try{body=JSON.parse(text)}catch{}return[r.status,body]};
function parseCSV(t){const rows=t.replace(/^\uFEFF/,'').trim().split(/\r?\n/);if(!rows.length)return[];const h=rows.shift().split(',').map(x=>x.trim().replace(/^\"|\"$/g,''));return rows.map(line=>{const v=[];let cur='',q=false;for(const ch of line){if(ch==='\"')q=!q;else if(ch===','&&!q){v.push(cur);cur=''}else cur+=ch}v.push(cur);const o={};h.forEach((k,i)=>o[k]=(v[i]||'').trim());return o})}
async function getNiftyRows(){let text='';try{const r=await fetchT(NSE,{headers:{'User-Agent':'Mozilla/5.0','Accept':'text/csv,*/*'}},5000);if(r.ok)text=await r.text()}catch(e){}if(!text){const r=await fetchT(FALLBACK,{headers:{'User-Agent':'Mozilla/5.0'}},5000);if(!r.ok)throw new Error(`Unable to load NIFTY 500 list (fallback HTTP ${r.status})`);text=await r.text();const parsed=parseCSV(text);return parsed.map(x=>({Symbol:x.Symbol||x.symbol})).filter(x=>x.Symbol)}const parsed=parseCSV(text);const headerKey=parsed.length&&Object.keys(parsed[0]).find(k=>k.toLowerCase()==='symbol');if(!headerKey)throw new Error('NIFTY 500 CSV format not recognised');return parsed.map(x=>({Symbol:x[headerKey]})).filter(x=>x.Symbol)}
async function instrumentMap(){const r=await fetchT(INS,{headers:{'Accept':'application/json'}},10000);if(!r.ok)throw new Error(`Upstox instrument master HTTP ${r.status}`);const {gunzipSync}=require('zlib');const i=JSON.parse(gunzipSync(Buffer.from(await r.arrayBuffer())).toString()).filter(x=>x.segment==='NSE_EQ'&&['EQ','BE'].includes(x.instrument_type));return new Map(i.map(x=>[String(x.trading_symbol||'').toUpperCase(),x]))}
async function universe(){const [rows,m]=await Promise.all([getNiftyRows(),instrumentMap()]);const out=[];for(const x of rows){const s=String(x.Symbol||'').trim().toUpperCase();const z=m.get(s);if(z)out.push({symbol:s,company:z.name||s,industry:'NIFTY 500',instrumentKey:z.instrument_key})}const seen=new Set();return out.filter(x=>!seen.has(x.symbol)&&seen.add(x.symbol)).slice(0,500)}
const candle=x=>({ts:x[0],o:+x[1],h:+x[2],l:+x[3],c:+x[4],v:+x[5]});
const exciting=x=>{const r=Math.max(x.h-x.l,1e-9);return Math.abs(x.c-x.o)/r>=.5};
const base=x=>{const r=Math.max(x.h-x.l,1e-9);return Math.abs(x.c-x.o)/r<.5};
function aggregateQuarterly(months){const a=months.map(candle).sort((a,b)=>a.ts.localeCompare(b.ts)),out=[];for(let i=0;i<a.length;i+=3){const g=a.slice(i,i+3);if(g.length<3)continue;out.push({ts:g[0].ts,o:g[0].o,h:Math.max(...g.map(x=>x.h)),l:Math.min(...g.map(x=>x.l)),c:g[g.length-1].c,v:g.reduce((s,x)=>s+x.v,0)})}return out}
function zones(raw){const c=raw.map(candle).sort((a,b)=>a.ts.localeCompare(b.ts)),out=[];for(let i=1;i<c.length-1;i++){const legIn=c[i-1],b=c[i],legOut=c[i+1];if(!base(b)||!exciting(legOut))continue;const demand=legOut.c>legOut.o;if(demand&&legIn.c>=legIn.o)continue;if(!demand&&legIn.c<=legIn.o)continue;const proximal=demand?Math.max(b.o,b.c):Math.min(b.o,b.c),distal=demand?b.l:b.h;let tested=false;for(let j=i+2;j<c.length;j++){if(c[j].h>=distal&&c[j].l<=proximal){tested=true;break}}const gap=demand?legOut.l>legIn.h:legOut.h<legIn.l;const strength=gap||exciting(legIn)?2:1;out.push({type:demand?'Demand':'Supply',proximal,distal,fresh:!tested,strength,score:Math.min(7,(!tested?3:0)+strength+2),ts:b.ts})}return out}
function weeklyTrend(raw){const c=raw.map(candle).sort((a,b)=>a.ts.localeCompare(b.ts));if(c.length<20)return'SIDEWAYS';const closes=c.map(x=>x.c);const ema=p=>{const k=2/(p+1);let e=closes[0];for(let i=1;i<closes.length;i++)e=closes[i]*k+e*(1-k);return e};const e20=ema(20),e50=ema(Math.min(50,closes.length)),last=closes.at(-1).c;if(last>e20&&e20>e50)return'UP';if(last<e20&&e20<e50)return'DOWN';return'SIDEWAYS'}
async function hist(key,unit,interval,years=5){const to=new Date().toISOString().slice(0,10);const d=new Date();if(unit==='hours')d.setDate(d.getDate()-75);else d.setFullYear(d.getFullYear()-years);const from=d.toISOString().slice(0,10);const[s,j]=await jget(`${API}/historical-candle/${encodeURIComponent(key)}/${unit}/${interval}/${to}/${from}`);if(s!==200)throw new Error(j?.errors?.[0]?.message||j?.message||`Upstox historical data ${s}`);return j?.data?.candles||[]}
async function scanOne(s,type){const masterRaw=await hist(s.instrumentKey,type==='QIT'?'months':'weeks',1,10),master=type==='QIT'?aggregateQuarterly(masterRaw):masterRaw,mz=zones(master).sort((a,b)=>b.score-a.score||String(b.ts).localeCompare(String(a.ts)))[0];if(!mz)return null;let trend='—';if(type==='MIT')trend=weeklyTrend(await hist(s.instrumentKey,'weeks',1,5));if(type==='MIT'&&((mz.type==='Demand'&&trend!=='UP')||(mz.type==='Supply'&&trend!=='DOWN')))return null;const unit=type==='QIT'?'weeks':type==='MIT'?'days':'hours',interval=type==='WIT'?'4':'1',eraw=await hist(s.instrumentKey,unit,interval,type==='WIT'?0.25:3),lo=Math.min(mz.proximal,mz.distal),hi=Math.max(mz.proximal,mz.distal),ez=zones(eraw).filter(z=>(z.proximal>=lo&&z.proximal<=hi)||(z.distal>=lo&&z.distal<=hi)).sort((a,b)=>b.score-a.score)[0];if(!ez)return null;const entry=ez.type==='Demand'?ez.proximal+.01:ez.proximal-.01,risk=Math.abs(entry-ez.distal);if(!risk)return null;const quality=Math.min(50,(mz.fresh?5:0)+(ez.fresh?5:0)+(mz.strength>=2?5:3)+(ez.strength>=2?5:3)+(((trend==='UP'&&ez.type==='Demand')||(trend==='DOWN'&&ez.type==='Supply'))?10:5)+5+(ez.score>=6?5:3)+5);return{symbol:s.symbol,company:s.company,industry:s.industry,instrumentKey:s.instrumentKey,type,direction:ez.type==='Demand'?'BUY':'SELL',zoneScore:Math.min(7,ez.score),quality,location:`${type} ${mz.type}`,trend,entryTf:type==='QIT'?'Weekly':type==='MIT'?'Daily':'4H',entry,sl:ez.distal,target:ez.type==='Demand'?entry+2*risk:entry-2*risk,rr:'1:2',masterZone:{proximal:mz.proximal,distal:mz.distal,score:mz.score,fresh:mz.fresh},entryZone:{proximal:ez.proximal,distal:ez.distal,score:ez.score,fresh:ez.fresh}}}
module.exports=async(q,r)=>{try{const u=new URL(q.url,'https://gtf.local'),a=u.searchParams.get('action')||'status';if(a==='status')return r.status(200).json({connected:!!token(),mode:token()?'analytics-token':'not-configured'});if(a==='universe')return r.status(200).json({data:await universe(),source:'NIFTY 500 + Upstox instrument master'});if(!token())return r.status(401).json({error:'UPSTOX_ANALYTICS_TOKEN is not configured in Vercel'});if(a==='ltp'){const keys=u.searchParams.get('keys');if(!keys)return r.status(400).json({error:'keys required'});const[s,j]=await jget(`${API}/market-quote/ltp?instrument_key=${encodeURIComponent(keys)}`);return r.status(s).json(j)}if(a==='scan'&&q.method==='POST'){let raw='';for await(const ch of q)raw+=ch;const b=JSON.parse(raw||'{}'),type=['QIT','MIT','WIT'].includes(b.type)?b.type:'MIT',all=Array.isArray(b.universe)?b.universe:[],offset=Math.max(0,+b.offset||0),limit=Math.min(25,Math.max(1,+b.limit||25)),slice=all.slice(offset,offset+limit),out=[];for(let i=0;i<slice.length;i+=5){const g=await Promise.all(slice.slice(i,i+5).map(s=>scanOne(s,type).catch(()=>null)));g.filter(Boolean).forEach(x=>out.push(x))}out.sort((a,b)=>b.zoneScore-a.zoneScore||b.quality-a.quality);return r.status(200).json({type,offset,limit,scanned:slice.length,total:all.length,done:offset+slice.length>=all.length,results:out})}return r.status(404).json({error:'Unknown action'})}catch(e){console.error(e);return r.status(500).json({error:e.name==='AbortError'?'Upstream request timed out':e.message||'Server error'})}};